plugins {
    id("com.android.application")
    id("com.chaquo.python")
}

android {
    namespace "org.packetproxy"
    compileSdk 31

    defaultConfig {
        applicationId "org.packetproxy"
        minSdk 21
        targetSdk 31
        versionCode 1
        versionName "2.0.0"

        ndk {
            abiFilters += "arm64-v8a"
        }

        python {
            version "3.8"
            pip {
                install "kivy==2.1.0"
                install "kivymd==0.104.2"
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    sourceSets {
        main {
            python.srcDir "src/main/python"
        }
    }
}

dependencies {
    implementation "androidx.core:core:1.9.0"
    implementation "androidx.appcompat:appcompat:1.6.1"
}
